apiVersion: apps/v1
kind: Deployment
metadata:
  name: pix-microservice-deployment
  labels:
    app: pix-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pix-microservice
  template:
    metadata:
      labels:
        app: pix-microservice
    spec:
      containers:
      - name: pix-microservice
        image: pix-microservice:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pix-microservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: pix-microservice